[project]
name = "burmese-ocr"
version = "0.1.0"
description = "Burmese OCR"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.9.2",
    "matplotlib>=3.10.1",
    "opencv-python>=4.11.0.86",
    "tensorflow>=2.19.0",
]
